### ISSUE TITLE
Bindgen generates different padding when cross-compiling based on host system

### ISSUE THREAD

**Issue by jdm** [rust-lang-nursery/rust-bindgen#1379]
As previously discussed on IRC (https://mozilla.logbot.info/servo/20180821#c15200737-c15201117), building [rust-mozjs](https://github.com/servo/rust-mozjs) on macOS when cross-compiling to Android (using NDK 12) causes the ForOfIterator to contain a padding value that is not present on our Linux->Android builds.

**Comment by emilio** [comment]
Unless https://github.com/servo/mozjs/pull/148 is not a fix for this, I think this is invalid. The problem is that the toolchain includes were not right, because the flags from:

  https://searchfox.org/mozilla-central/rev/c3fef66a5b211ea8038c1c132706d02db408093a/build/moz.configure/android-ndk.configure#324

Weren't being accounted for.

**Comment by emilio** [comment]
Closing for now, but let's reopen if there's a deeper issue here.
