### ISSUE TITLE
Error after updating Unix system

### ISSUE THREAD

**Issue by trsh** [rust-lang-nursery/rust-bindgen#1426]
RUST_BACKTRACE=1 bindgen soapStub.h -o binding.rs --whitelist-type xxx
/usr/include/stdlib.h:31:10: fatal error: 'stddef.h' file not found, err: true

Any advice?

**Update**

I created some symlinks, bet the it's next fatal error: 'stdarg.h' file not found, err:. Seems like a never ending story.

**Comment by trsh** [comment]
I created some symlinks, bet the it's next `fatal error: 'stdarg.h' file not found, err:`. Seems like a never ending story.

**Comment by trsh** [comment]
This saved my day

export C_INCLUDE_PATH=/usr/lib/llvm-6.0/lib/clang/6.0.0/include"${C_INCLUDE_PATH+:}${C_INCLUDE_PATH-}"

**Comment by emilio** [comment]
Looks like that should be detected automatically by clang-sys though... What system are you on?

**Comment by trsh** [comment]
@emilio Ubuntu 10.x

**Comment by alex88** [comment]
@trsh thank you you comment saved me after hours trying to debug this!

**Comment by emilio** [comment]
(FWIW, comment edits don't arrive to my email notifications, so you were just lucky that I saw your mention :))

I think it's resolved now per your latest edits, but if it still happens when there's a usable clang / libclang in the system it should be filed upstream in https://github.com/kylemayes/clang-sys, which is what bindgen uses to find the library.

**Comment by alex88** [comment]
@emilio woops sorry :) Anyway, it is solved because I've installed the clang binary package, you think is still worth opening an issue on clang-sys? I'm a rust beginner so I'm not exactly sure what to do here but if it's something that's supposed to work maybe I should open one
