### ISSUE TITLE
Bitfield constructors aren't very convenient when the bitfield is internally represented as an array.

### ISSUE THREAD

**Issue by emilio** [rust-lang-nursery/rust-bindgen#735]
See the integration tests modification in the incoming PR.

**Comment by emilio** [comment]
It should probably use `field_ty`, instead of hardcoding its own field.

**Comment by emilio** [comment]
(That being said, that prevents it from being `const` most of the time, we'd need to manually implement the equivalent of `transmute`).

**Comment by fitzgen** [comment]
Yes, I've run into this as well. Started making everything `lazy_static! { ... }` instead of `const`, which is also sad.

@Manishearth suggested just generating multiple copies of the `<code-that-generates-unit-field-int-type>` for each array element and then `&`ing each element's value out. It would work, but would be pretty gross IMO.

**Comment by fitzgen** [comment]
Also, clearly `transmute` should be considered a `const fn`.

**Comment by emilio** [comment]
Yeah, I think transmute and zeroed should be const as well.

**Comment by fitzgen** [comment]
This is fixed with `__BindgenBitfieldUnit`
