### ISSUE TITLE
Make BindgenOptions be pub(crate)

### ISSUE THREAD

**Issue by fitzgen** [rust-lang-nursery/rust-bindgen#958]
Its public use has been deprecated for a while now, and it is only meant for internal use.

**Comment by pepyakin** [comment]
@highfive: assign me
@fitzgen 

https://github.com/rust-lang-nursery/rust-bindgen/blob/ab6d51bb431665b53ec0c0d2370cd1f3d0e372f6/src/lib.rs#L10-L12

This comment actually is not accurate, because deprecated `Bindings::generate` is used here:

https://github.com/rust-lang-nursery/rust-bindgen/blob/ab6d51bb431665b53ec0c0d2370cd1f3d0e372f6/src/lib.rs#L1015

Should I also make it `pub(crate)`?
